### ISSUE TITLE
Exception while running standalone JAR

### ISSUE THREAD

**Issue by cagataygurturk** [invesdwin/invesdwin-instrument#1]
Hello,

I am new to Java, trying to use this library but I've a problem.

When I run my application from IntelliJ the library works like a charm, all @Configurable annotated classes has their independence via AspectJ. But the problem appears when I compile to JAR with 

```
$ mvn install
```

After that I try to run the JAR file. 

```
$ java -jar target/api-0.0.2.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.instela.InstelaApiApplication.<clinit>(InstelaApiApplication.java:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: no entry name specified
    at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:94)
    ... 7 more
Caused by: java.io.IOException: no entry name specified
    at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:177)
    at java.net.URL.openStream(URL.java:1038)
    at de.invesdwin.instrument.DynamicInstrumentationLoader.createTempAgentJar(DynamicInstrumentationLoader.java:116)
    at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:63)
    ... 7 more
```

I understand that the library tries to write to file system but it can't but I could not figure out the exact problem. Am I missing a point?

**Comment by subes** [comment]
The error occurs because it cannot fetch the agent class file "de.invesdwin.instrument.internal.DynamicInstrumentationAgent" from the jar it resides in. How is it packaged in your case? Normally I would expect a command like this to launch the application:

```
java -jar target/api-0.0.2.jar -cp /PATH/TO/invesdwin-instrument-VERSION.jar
```

If the files were missing you should get a ClassNotFoundException, so I guess you somehow repackaged the classes. If really you repackaged the invesdwin-instrument.jar into your api-0.0.2.jar, then maybe your repackaging mechanism is broken?
- Repackaging of libraries does not work well with [one-jar](https://code.google.com/archive/p/onejar-maven-plugin/), if you are using this. It has lots of problems with classpath reflection and direct jar access. 
- I would recommend [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) instead, but to get spring and other frameworks working, you have to register a lot of transformers there to merge config files.
- Otherwise if you copy/pasted the code into your project, maybe you are missing something.

In any way, it should work when not repackaging the library and setting up a proper classpath to launch the application. If it still does not work, you can always go the safe route to register the javaagent jar via the [-javaagent](http://stackoverflow.com/a/11898653/67492) launch parameter. Then just provide a launch script for your application.

If I am way off here, I need more info, a sample project to reproduce the problem would help.

**Comment by subes** [comment]
Well, since there is no comment on this one, I am considering this as closed. Reopen if you have any more issues with this.
