### ISSUE TITLE
Spring Boot 2.3.x support

### ISSUE THREAD

**Issue by herdemir** [invesdwin/invesdwin-instrument#16]
Hi,

After upgrading my project to spring boot 2.3 i was getting the following error:

`Exception in thread "main" java.lang.NoSuchMethodError: org.assertj.core.api.AbstractBooleanAssert.as(Ljava/lang/String;[Ljava/lang/Object;)Lorg/assertj/core/api/AbstractAssert;
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:68)
	at de.invesdwin.instrument.DynamicInstrumentationLoader.setAgentClassLoaderReference(DynamicInstrumentationLoader.java:154)
	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:77)`

`org.assertj.core:assertj-core` library seems to be upgraded in spring boot 2.3. A new release with simple recompilation against that version should probably fix this issue.

Edit: The assertj-core dependency comes with `spring-boot-starter-actuator`

**Comment by subes** [comment]
I have released invesdwin-instrument-1.0.9 which fixes this. I decided to remove the depenceny on assertj so that these incompatibilities do not occur again with invesdwin-instrument. Thanks for reporting this!
