### ISSUE TITLE
java.lang.NoSuchFieldException: ucp (JDK-16)

### ISSUE THREAD

**Issue by andreak** [invesdwin/invesdwin-instrument#19]
With openjdk-16 I get this Exception:

```
 Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp
         at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:111)
         ... 19 more
 Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp
         at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:90)
         at de.invesdwin.instrument.DynamicInstrumentationLoader.setAgentClassLoaderReference(DynamicInstrumentationLoader.java:157)
         at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:80)
         ... 19 more
 Caused by: java.lang.NoSuchFieldException: ucp
         at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
         at de.invesdwin.instrument.DynamicInstrumentationReflections.addUrlToAppClassLoaderURLClassPath(DynamicInstrumentationReflections.java:114)
         at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:75)
         ... 21 more
```
Any ideas?

**Comment by subes** [comment]
Thanks for the pull request. I will review the changes this week and publish a new release.

**Comment by subes** [comment]
Version 1.0.10 has been released. Thanks for the fix!

**Comment by andreak** [comment]
Coolio, keep on rocking!
