### ISSUE TITLE
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by mavicmor** [invesdwin/invesdwin-instrument#21]
Hi,
Sometimes, not always, we are having this exception when the applications starts in Tomcat. The context is: 

- Tomcat 8
- Architecture: Spring boot2
- We have several applications that load invesdwin-instrument dynamically.
- Tomcat start several applications in parallel:
  <Host name="localhost"  appBase="webapps"
              unpackWARs="true" autoDeploy="true" deployOnStartup="false" **startStopThreads="0"**>

Exception:
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.NullPointerException
        at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.premain(DynamicInstrumentationAgent.java:13)
        at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.agentmain(DynamicInstrumentationAgent.java:21)
        ... 6 more
Agent failed to start!

Thank you very much!

**Comment by subes** [comment]
I have implemented a fix for potential race conditions when multiple different instrumentation loads for different instrumentation contexts (webapps) are used:
https://github.com/invesdwin/invesdwin-instrument/commit/1e20cbc9f284eabbcaea10434c6962e5d93e11db

**Comment by subes** [comment]
This will isolate each agent load by different UUIDs. I am preparing a release for this fix. With that you can test if this resolves your occasional exceptions.

**Comment by mavicmor** [comment]
Thank you very much Edwin! When the new release is available I will test the solution and send you the feedback.

**Comment by subes** [comment]
invesdwin-instrument-1.0.11 is now available.

Please reopen the ticket if there is a problem with the fix.

**Comment by mavicmor** [comment]
Hi Edwin, in this version 1.0.11, we are having this exception **always** when several applications load invesdwin-instrument dynamically. The agent is loaded ok in the first one application, but fail when load the second one application. The behavior is worse than the previous version. This version have the same behaviour without startStopThreads="0"
Exception:
 INFORMACIËN: 2 Spring WebApplicationInitializers detected on classpath
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.ClassNotFoundException: de.invesdwin.instrument.internal.AgentInstrumentationInitializer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.premain(DynamicInstrumentationAgent.java:24)
        at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.agentmain(DynamicInstrumentationAgent.java:42)
        ... 6 more
Agent failed to start!
Exception in thread "Thread-13" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at de.invesdwin.instrument.DynamicInstrumentationLoader$1.run(DynamicInstrumentationLoader.java:93)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at de.invesdwin.instrument.internal.DynamicInstrumentationLoadAgentMain.loadAgent(DynamicInstrumentationLoadAgentMain.java:56)
        at de.invesdwin.instrument.DynamicInstrumentationLoader.loadAgent(DynamicInstrumentationLoader.java:122)
        at de.invesdwin.instrument.DynamicInstrumentationLoader.access$000(DynamicInstrumentationLoader.java:31)
        at de.invesdwin.instrument.DynamicInstrumentationLoader$1.run(DynamicInstrumentationLoader.java:90)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.invesdwin.instrument.internal.DynamicInstrumentationLoadAgentMain.loadAgent(DynamicInstrumentationLoadAgentMain.java:49)
        ... 3 more
 java.lang.IllegalStateException: Error starting child
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:716)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1620)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1144)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1346)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1350)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1328)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/ovia2-properties-presentation]]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
        ... 25 more
Caused by: java.lang.RuntimeException: Additional information: javaVersion=1.8.0_131; javaHome=C:\DESARROLLO_OVIA2\Jba-jcyl\jdk1.8.0_131\jre; toolsJarPath=C:\DESARROLLO_OVIA2\Jba-jcyl\jdk1.8.0_131\lib\tools.jar; attachLibPath=C:\DESARROLLO_OVIA2\Jba-jcyl\jdk1.8.0_131\jre\bin\attach.dll
        at de.invesdwin.instrument.DynamicInstrumentationLoader.waitForInitialized(DynamicInstrumentationLoader.java:56)
        at es.jcyl.PropertiesPresentationApplication.configure(PropertiesPresentationApplication.java:23)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:138)
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5139)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 26 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at de.invesdwin.instrument.internal.DynamicInstrumentationLoadAgentMain.loadAgent(DynamicInstrumentationLoadAgentMain.java:56)
        at de.invesdwin.instrument.DynamicInstrumentationLoader.loadAgent(DynamicInstrumentationLoader.java:122)
        at de.invesdwin.instrument.DynamicInstrumentationLoader.access$000(DynamicInstrumentationLoader.java:31)
        at de.invesdwin.instrument.DynamicInstrumentationLoader$1.run(DynamicInstrumentationLoader.java:90)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.invesdwin.instrument.internal.DynamicInstrumentationLoadAgentMain.loadAgent(DynamicInstrumentationLoadAgentMain.java:49)
        ... 3 more
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:540)
        ... 8 more

Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:540)
        ... 8 more

Thank you very much.

**Comment by subes** [comment]
`Caused by: java.lang.ClassNotFoundException: de.invesdwin.instrument.internal.AgentInstrumentationInitializer
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.premain(DynamicInstrumentationAgent.java:24)
at de.invesdwin.instrument.internal.DynamicInstrumentationAgent.agentmain(DynamicInstrumentationAgent.java:42)
... 6 more`
This seems to be the root cause. Will look into it.

**Comment by subes** [comment]
invesdwin-instrument-1.0.13 is now available. I found a more robust way to pass the uuid for the classloader reference to the agentMain by compiling it directly into the agent class. That way the class is unique and won't be reused by other webapps being loaded.
Sadly attach API does not support passing arguments to an agent and arguments can also not be defined inside the manifest.mf as far as I could see. That is why this workaround is needed.

Please reopen the ticket if there is a new problem with the fix.

**Comment by mavicmor** [comment]
Thank you very much Edwin! That works!! Good job!
I will test the behavior during this month and send you the feedback.
