### ISSUE TITLE
Issue to update to 1.0.13 from 1.0.11

### ISSUE THREAD

**Issue by sayseakleng** [invesdwin/invesdwin-instrument#23]
Here there!
I've encounter an issue when I'm trying to upgrade my spring boot project from  **invesdwin-instrument-1.0.13** from **invesdwin-instrument-1.0.11** as following:

DynamicInstrumentationCompiler\DynamicInstrumentationAgent_7eb702271abd4a449b1148518279604a.java:7: warning: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

public final class DynamicInstrumentationAgent_7eb702271abd4a449b1148518279604a {
             ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:419)

  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:90)

  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:124)

  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:177)

  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)

  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)

  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)

  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)

  	at com.sun.tools.javac.main.Main.compile(Main.java:523)

  	at com.sun.tools.javac.main.Main.compile(Main.java:381)

  	at com.sun.tools.javac.main.Main.compile(Main.java:370)

  	at com.sun.tools.javac.main.Main.compile(Main.java:361)

  	at com.sun.tools.javac.Main.compile(Main.java:74)

  	at com.sun.tools.javac.api.JavacTool.run(JavacTool.java:237)

  	at de.invesdwin.instrument.internal.compile.DynamicInstrumentationCompiler.compile(DynamicInstrumentationCompiler.java:78)

  	at de.invesdwin.instrument.internal.DynamicInstrumentationAgentCompiler.compile(DynamicInstrumentationAgentCompiler.java:25)

  	at de.invesdwin.instrument.DynamicInstrumentationLoader.createTempAgentJar(DynamicInstrumentationLoader.java:171)

  	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:82)

  	at com.test.server.Application.main(Application.java:20)

  Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.processing.JavacProcessingEnvironment

  	at java.lang.ClassLoader.findClass(ClassLoader.java:523)

  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

  	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:534)

  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

  	... 24 more

Look forward to your response.

Regards.

**Comment by subes** [comment]
which java version are you using?

**Comment by subes** [comment]
Though the issue seems to be caused by Lombok:
https://github.com/ThinkingLogic/kotlin-builder-annotation/issues/5

But I guess I will implement a fallback. So that when the class compilation fails, the old method with the precompiled class will be used. But I guess using lombok+invesdwin-instrument+tomcat won't work in that case. Though I would say that is a corner case anyway.

**Comment by sayseakleng** [comment]
> which java version are you using?

Thank you so much @subes for your prompt response.
My environment here is:
- JDK: 1.8
- Lombok: 1.18.12
- Spring Boot: 2.3.12

For your reference, it works normally on **invesdwin V 1.0.11** with the same environment.

Your Regards.

**Comment by subes** [comment]
invesdwin-instrument-1.0.14 is now available.
I implemented the following fallback mechanism:
1. 25 shots for precompiled agents, so that lombok+tomcat+invesdwin-instrument works in most cases
2. after the 25 shots, we try to dynamically compile additional classes
3. if the dynamic compilation failed, the default agent will be used

Hope this covers most use cases. Step 1. should be as robust as step 3. and I guess it would be rare to deploy more than a few instrumented apps inside a container. Though step 3. will most likely not work properly in tomcat and other JVM containers. Though it should work as a fallback for standalone spring-boot apps (meaning running one app in one JVM).

Please reopen the ticket if you have issues with the new version.
