### ISSUE TITLE
Spring boot + Tomcat 8.5 integration

### ISSUE THREAD

**Issue by teikitel** [invesdwin/invesdwin-instrument#5]
Hi, I used invesdwin-instrument to Instrument some classes from a dependency I have. Integrating it with Spring Boot on a Tomcat 8.5 (didn't try on previous version) I faced this issue : 
```
Caused by: java.lang.IllegalStateException: No LoadTimeWeaver available
        at org.springframework.context.weaving.AspectJWeavingEnabler.enableAspectJWeaving(AspectJWeavingEnabler.java:86)
        at org.springframework.context.weaving.AspectJWeavingEnabler.postProcessBeanFactory(AspectJWeavingEnabler.java:71)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:169)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 10 more
```

I solved this by using `@EnableLoadTimeWeaving` annotation. So my confirguation is now : 

```
@SpringBootApplication
@EnableLoadTimeWeaving // instead of @ImportResource(locations = "classpath:/META-INF/ctx.spring.weaving.xml")
public class MySpringBootApplication {
    public static void main(final String[] args) {
        DynamicInstrumentationLoader.waitForInitialized(); //dynamically attach java agent to jvm if not already present
        DynamicInstrumentationLoader.initLoadTimeWeavingContext(); //weave all classes before they are loaded as beans
        SpringApplication.run(MySpringBootApplication.class, args); //start application, load some classes
    }
}
```

Best regards,
Loïc

**Comment by subes** [comment]
Which version of spring-boot are you using? Maybe they changed something in the meantime?

**Comment by teikitel** [comment]
Spring Boot v1.5.7.RELEASE, Spring v4.3.11.RELEASE

**Comment by subes** [comment]
I have adjusted the documentation. Thanks for the report.
