### ISSUE TITLE
JDK 11 support

### ISSUE THREAD

**Issue by MichailIsaev** [invesdwin/invesdwin-instrument#9]
What about it? Now i have this stacktrace:
`	
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: urls
	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:108)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: urls
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:62)
	at de.invesdwin.instrument.DynamicInstrumentationLoader.setAgentClassLoaderReference(DynamicInstrumentationLoader.java:154)
	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:77)
	... 1 more
Caused by: java.lang.NoSuchFieldException: urls
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addUrlToAppClassLoaderURLClassPath(DynamicInstrumentationReflections.java:93)
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:47)
	... 3 more
`

**Comment by subes** [comment]
I have released version 1.0.2 which includes the code that was changed in https://github.com/subes/invesdwin-instrument/issues/6 

Please verify that this works for you.

**Comment by MichailIsaev** [comment]
This works for me. Thanks you.
